export const data=[{
    "id": 1,
    "first_name": "Arlee",
    "last_name": "Avraam",
    "email": "aavraam0@usnews.com",
    "gender": "Female"
  }, {
    "id": 2,
    "first_name": "Marijo",
    "last_name": "Largan",
    "email": "mlargan1@jimdo.com",
    "gender": "Female"
  }, {
    "id": 3,
    "first_name": "Erik",
    "last_name": "Brosenius",
    "email": "ebrosenius2@skyrock.com",
    "gender": "Male"
  }, {
    "id": 4,
    "first_name": "Andras",
    "last_name": "Pudney",
    "email": "apudney3@devhub.com",
    "gender": "Male"
  }, {
    "id": 5,
    "first_name": "Carlos",
    "last_name": "Dyshart",
    "email": "cdyshart4@blog.com",
    "gender": "Male"
  }, {
    "id": 6,
    "first_name": "Ives",
    "last_name": "Buddle",
    "email": "ibuddle5@surveymonkey.com",
    "gender": "Genderfluid"
  }, {
    "id": 7,
    "first_name": "Alasteir",
    "last_name": "Boorer",
    "email": "aboorer6@icio.us",
    "gender": "Male"
  }, {
    "id": 8,
    "first_name": "Julee",
    "last_name": "Tunnoch",
    "email": "jtunnoch7@wp.com",
    "gender": "Female"
  }, {
    "id": 9,
    "first_name": "Eileen",
    "last_name": "Packe",
    "email": "epacke8@va.gov",
    "gender": "Female"
  }, {
    "id": 10,
    "first_name": "Alyssa",
    "last_name": "Rutland",
    "email": "arutland9@issuu.com",
    "gender": "Female"
  }, {
    "id": 11,
    "first_name": "Temple",
    "last_name": "Linnell",
    "email": "tlinnella@hibu.com",
    "gender": "Male"
  }, {
    "id": 12,
    "first_name": "Sean",
    "last_name": "Hollingshead",
    "email": "shollingsheadb@deviantart.com",
    "gender": "Male"
  }, {
    "id": 13,
    "first_name": "Vannie",
    "last_name": "Swanne",
    "email": "vswannec@addtoany.com",
    "gender": "Female"
  }, {
    "id": 14,
    "first_name": "Alvy",
    "last_name": "Carpe",
    "email": "acarped@webmd.com",
    "gender": "Male"
  }, {
    "id": 15,
    "first_name": "Vassily",
    "last_name": "Downage",
    "email": "vdownagee@washington.edu",
    "gender": "Male"
  }, {
    "id": 16,
    "first_name": "Lauren",
    "last_name": "Barradell",
    "email": "lbarradellf@macromedia.com",
    "gender": "Female"
  }, {
    "id": 17,
    "first_name": "Harlan",
    "last_name": "Lucy",
    "email": "hlucyg@ehow.com",
    "gender": "Male"
  }, {
    "id": 18,
    "first_name": "Georgeta",
    "last_name": "Goudge",
    "email": "ggoudgeh@nytimes.com",
    "gender": "Female"
  }, {
    "id": 19,
    "first_name": "Robbert",
    "last_name": "Langelay",
    "email": "rlangelayi@behance.net",
    "gender": "Male"
  }, {
    "id": 20,
    "first_name": "Muffin",
    "last_name": "Issac",
    "email": "missacj@irs.gov",
    "gender": "Genderfluid"
  }]
